
const FILTER_CATEGORIES = {
  "Tech & Digital Careers": [
    "Software Engineering",
    "Prompt Engineering",
    "Tech Sales",
    "IT",
    "Web Development",
    "UI/UX Design",
    "Cloud Computing",
    "AI Researcher",
    "Blockchain Developer",
    "Ethical Hacking",
    "IT Support Specialist",
    "Network Engineering",
    "DevOps Engineering",
    "Mobile App Development",
  ],
  "Content Creation": [
    "Gamer",
    "Youtuber",
    "Book Readers",
    "News",
    "Journalism",
  ],
  "Business & Sales": [
    "Business Consulting",
    "Product Management",
    "Venture Capitalist",
    "Real Estate Agent",
    "E-commerce Seller",
    "Copywriting",
    "Business Coaching",
    "Affiliate Marketing",
    "Customer Success Manager",
    "Public Relations",
  ],
  "Creative Fields": [
    "Video Editing",
    "Animation",
    "Acting",
    "Voice Acting",
    "Scriptwriting",
    "Film Directing",
    "Interior Design",
    "3D Modeling",
    "Fashion Design",
    "Illustration",
  ],
  "Finance & Investing": [
    "Accounting",
    "Financial Planning",
    "Forex Trading",
    "Cryptocurrency Investing",
    "Private Equity",
    "Risk Management",
    "Insurance Brokerage",
    "Hedge Fund Management",
    "Corporate Finance",
    "Credit Analysis",
  ],
  "Health & Wellness": [
    "Personal Training",
    "Nutrition Coaching",
    "Yoga Instruction",
    "Physical Therapy",
    "Mental Health Counseling",
    "Medical Coding",
    "Sports Coaching",
    "Healthcare Administration",
    "Alternative Medicine",
    "Meditation Coaching",
  ],
  "Science & Engineering": [
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Robotics",
    "Civil Engineering",
    "Mechanical Engineering",
    "Chemistry Research",
    "Physics Research",
    "Environmental Science",
    "Biotechnology",
    "Marine Biology",
  ],
  "Software Development": [
    "Frontend Developer",
    "Backend Developer",
    "Full-Stack Developer",
    "Game Developer",
    "Embedded Systems Engineer",
    "API Developer",
    "Software Architect",
    "Open Source Contributor",
    "Test Automation Engineer",
    "Low-Code/No-Code Developer",
  ],
  "AI & Machine Learning": [
    "AI Engineer",
    "Deep Learning Engineer",
    "Computer Vision Engineer",
    "NLP Engineer",
    "AI Ethics Researcher",
    "Reinforcement Learning Engineer",
    "AI Chatbot Developer",
    "Generative AI Specialist",
    "Data Annotation Specialist",
    "AI Product Manager",
  ],
  "Data Science": [
    "Data Analyst",
    "Data Engineer",
    "MLOps Engineer",
    "Business Intelligence Analyst",
    "Data Visualization Specialist",
    "Database Administrator",
    "Big Data Engineer",
    "ETL Developer",
    "Predictive Analytics Expert",
    "Data Governance Specialist",
  ],
  "Cybersecurity": [
    "Penetration Tester",
    "Security Analyst",
    "Security Engineer",
    "Cyber Threat Intelligence Analyst",
    "Network Security Engineer",
    "Cloud Security Engineer",
    "Incident Response Analyst",
    "SOC Analyst",
    "Digital Forensics Analyst",
    "Cryptography Engineer",
  ],
  "Cloud & DevOps": [
    "Cloud Architect",
    "Cloud Engineer",
    "Site Reliability Engineer",
    "DevOps Engineer",
    "Kubernetes Specialist",
    "Infrastructure as Code Engineer",
    "Serverless Computing Engineer",
    "Platform Engineer",
    "Multi-Cloud Specialist",
    "Edge Computing Engineer",
  ],
  "Blockchain & Web3": [
    "Blockchain Developer",
    "Smart Contract Developer",
    "Web3 Developer",
    "Crypto Analyst",
    "DeFi Developer",
    "NFT Developer",
    "Consensus Algorithm Engineer",
    "Layer 2 Scaling Engineer",
    "DAO Specialist",
    "Metaverse Developer",
  ],
  "Other": [
    "Youth Adult",
    "Other Interests",
  ]
};

export default FILTER_CATEGORIES;
