
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcywiyvbfrylffwfzsny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjeXdpeXZiZnJ5bGZmd2Z6c255Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0ODA3MDIsImV4cCI6MjA1MzA1NjcwMn0.rZUZjLf4j6h0lhl53PhKJ0eARsBXdmlPOtIAHTJQxNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a helper function to enable realtime on tables we need
export const enableRealtimeForTables = () => {
  supabase.channel('schema-db-changes')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'post_reactions' }, (payload) => {
      console.log('Reaction changes detected', payload);
    })
    .on('postgres_changes', { event: '*', schema: 'public', table: 'post_bludifies' }, (payload) => {
      console.log('Bludify changes detected', payload);
    })
    .on('postgres_changes', { event: '*', schema: 'public', table: 'post_bookmarks' }, (payload) => {
      console.log('Bookmark changes detected', payload);
    })
    .on('postgres_changes', { event: '*', schema: 'public', table: 'notifications' }, (payload) => {
      console.log('Notification changes detected', payload);
    })
    .subscribe();
};

// Helper function to convert arrays to JSON strings for Supabase storage
export const prepareArrayField = (field: string[]): string => {
  return JSON.stringify(field);
};

// Helper function to parse JSON strings from Supabase to arrays
export const parseArrayField = (field: string | null): string[] => {
  if (!field) return [];
  try {
    // Try to parse as JSON array
    const parsed = JSON.parse(field);
    return Array.isArray(parsed) ? parsed : [field];
  } catch (error) {
    // If it's not valid JSON, return it as a single item array
    return [field];
  }
};

// Function to find and extract company mentions from post content
export const extractCompanyMentions = (content: string): string[] => {
  // Regular expression to detect @company pattern
  const mentionRegex = /@(\w+)/g;
  
  // Find all matches
  const matches = [...content.matchAll(mentionRegex)];
  
  // Extract company names from matches
  return matches.map(match => match[1].toLowerCase().trim());
};

// Function to create a notification for company members
export const notifyCompanyMembers = async (
  senderId: string, 
  companyName: string, 
  postContent: string, 
  postId: string
): Promise<void> => {
  try {
    // Find all users who have this company in their profile
    const { data: profilesWithCompany, error: profilesError } = await supabase
      .from('profiles')
      .select('user_id, company')
      .not('user_id', 'eq', senderId); // Exclude the sender
    
    if (profilesError) {
      console.error('Error fetching profiles:', profilesError);
      return;
    }
    
    // Filter users who have the tagged company in their company list
    const usersToNotify = profilesWithCompany.filter(profile => {
      const companies = parseArrayField(profile.company);
      return companies.some(company => 
        company.toLowerCase() === companyName.toLowerCase()
      );
    });
    
    console.log(`Found ${usersToNotify.length} users to notify for company: ${companyName}`);
    
    // Prepare notification data
    const notifications = usersToNotify.map(profile => ({
      type: 'company_mention',
      recipient_id: profile.user_id,
      sender_id: senderId,
      content: `mentioned ${companyName} in a post`,
      metadata: {
        company: companyName,
        post_id: postId,
        post_excerpt: postContent.substring(0, 100) + (postContent.length > 100 ? '...' : '')
      },
      is_read: false
    }));
    
    // Insert notifications
    if (notifications.length > 0) {
      const { error: notificationError } = await supabase
        .from('notifications')
        .insert(notifications);
      
      if (notificationError) {
        console.error('Error creating notifications:', notificationError);
      } else {
        console.log(`Created ${notifications.length} notifications for company: ${companyName}`);
      }
    }
  } catch (error) {
    console.error('Error in notifyCompanyMembers:', error);
  }
};
